/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.Manager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Umut
 */
public class CreditApplication extends javax.swing.JFrame {

    private String[] userData;
    private Manager manager;
    private DefaultTableModel dtm;
    /**
     * Creates new form CreditApplication
     */
    public CreditApplication(String[] userData) {
        initComponents();
        setLocationRelativeTo(null);
        
        manager = new Manager();
        this.userData = userData;
        
        String[] creditUserIDs = manager.getCreditIDs();
        for(int i = 0; i < creditUserIDs.length; i++)
            if(creditUserIDs[i] != null) creditComboBox.addItem(creditUserIDs[i]);
        
        dtm = new DefaultTableModel(0, 0);
        String header[] = new String[] {"id","Ad Soyad","Miktar","Kredi Türü"};
        dtm.setColumnIdentifiers(header);
        creditsTable.setModel(dtm);
        
        String[][] credits = manager.getCredits();
        for (int i = 0; i < credits.length; i++)
            if(credits[i][0] != null) dtm.addRow(credits[i]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        anaEkranText3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        creditsTable = new javax.swing.JTable();
        creditComboBox = new javax.swing.JComboBox<>();
        onaylaButon = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        reddetButon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kredi Başvuruları");

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        anaEkranText3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        anaEkranText3.setText("Kredi Başvuruları");

        creditsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(creditsTable);

        creditComboBox.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        onaylaButon.setBackground(new java.awt.Color(0, 204, 102));
        onaylaButon.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        onaylaButon.setForeground(new java.awt.Color(255, 255, 255));
        onaylaButon.setText("Onayla");
        onaylaButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onaylaButonActionPerformed(evt);
            }
        });

        backButton.setText("Ana Ekrana Dön");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("ID:");

        reddetButon.setBackground(new java.awt.Color(255, 51, 51));
        reddetButon.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        reddetButon.setForeground(new java.awt.Color(255, 255, 255));
        reddetButon.setText("Reddet");
        reddetButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reddetButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(creditComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(onaylaButon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reddetButon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(anaEkranText3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(anaEkranText3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onaylaButon)
                    .addComponent(jLabel1)
                    .addComponent(reddetButon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(backButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onaylaButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onaylaButonActionPerformed
        String[] response = manager.applyOrRejectCredit(creditComboBox.getSelectedItem().toString(), 1);

        if(response[0].equals("true")) {
            creditComboBox.removeAllItems();
            String[] creditUserIDs = manager.getCreditIDs();
            for(int i = 0; i < creditUserIDs.length; i++)
                if(creditUserIDs[i] != null) creditComboBox.addItem(creditUserIDs[i]);
            
            dtm = new DefaultTableModel(0, 0);
            String header[] = new String[] {"id","Ad Soyad","Miktar","Kredi Türü"};
            dtm.setColumnIdentifiers(header);
            creditsTable.setModel(dtm);
            
            String[][] credits = manager.getCredits();
            for (int i = 0; i < credits.length; i++)
                if(credits[i][0] != null) dtm.addRow(credits[i]);

            JOptionPane.showMessageDialog(this, response[1], "Onaylandı", 1);
        }
        else {
            JOptionPane.showMessageDialog(this, response[1], "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_onaylaButonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new ManagerDashboard(userData).setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void reddetButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reddetButonActionPerformed
        String[] response = manager.applyOrRejectCredit(creditComboBox.getSelectedItem().toString(), -1);

        if(response[0].equals("true")) {
            creditComboBox.removeAllItems();
            String[] creditUserIDs = manager.getCreditIDs();
            for(int i = 0; i < creditUserIDs.length; i++)
                if(creditUserIDs[i] != null) creditComboBox.addItem(creditUserIDs[i]);
            
            dtm = new DefaultTableModel(0, 0);
            String header[] = new String[] {"id","Ad Soyad","Miktar","Kredi Türü"};
            dtm.setColumnIdentifiers(header);
            creditsTable.setModel(dtm);
        
            String[][] credits = manager.getCredits();
            for (int i = 0; i < credits.length; i++)
                if(credits[i][0] != null) dtm.addRow(credits[i]);

            JOptionPane.showMessageDialog(this, response[1], "Reddedildi", 1);
        }
        else {
            JOptionPane.showMessageDialog(this, response[1], "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_reddetButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String[] userData = {"id","ad soyad","200"};
                new CreditApplication(userData).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anaEkranText1;
    private javax.swing.JLabel anaEkranText2;
    private javax.swing.JLabel anaEkranText3;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> creditComboBox;
    private javax.swing.JTable creditsTable;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton onaylaButon;
    private javax.swing.JButton onaylaButton;
    private javax.swing.JButton onaylaButton1;
    private javax.swing.JButton reddetButon;
    private javax.swing.JTable usersTable;
    private javax.swing.JTable usersTable1;
    // End of variables declaration//GEN-END:variables
}
