/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

/**
 *
 * @author Umut
 */
public class CustomerDashboard extends javax.swing.JFrame {

    private String[] userData;
    /**
     * Creates new form DashboardJFrame
     */
    public CustomerDashboard(String[] userData) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.userData = userData;
        fullNameText.setText(userData[1]);
        balanceText.setText(userData[2] + " ₺");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        anaEkranText = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        sifreDegistirButton = new javax.swing.JButton();
        hesapButton = new javax.swing.JButton();
        paraTransferiButton = new javax.swing.JButton();
        faturaButton = new javax.swing.JButton();
        krediKartiButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        krediBasvuruButton = new javax.swing.JButton();
        fullNameText = new javax.swing.JLabel();
        balanceText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Müşteri Ana Ekranı");

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        anaEkranText.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        anaEkranText.setText("Ana Ekran");

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        sifreDegistirButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        sifreDegistirButton.setText("Şifre Değiştir");
        sifreDegistirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifreDegistirButtonActionPerformed(evt);
            }
        });

        hesapButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        hesapButton.setText("Hesap İşlemleri");
        hesapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesapButtonActionPerformed(evt);
            }
        });

        paraTransferiButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        paraTransferiButton.setText("Para Transferi");
        paraTransferiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paraTransferiButtonActionPerformed(evt);
            }
        });

        faturaButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        faturaButton.setText("Fatura Ödeme");
        faturaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faturaButtonActionPerformed(evt);
            }
        });

        krediKartiButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        krediKartiButton.setText("Kredi Kartı");
        krediKartiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krediKartiButtonActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(255, 0, 51));
        logoutButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Çıkış Yap");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        krediBasvuruButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        krediBasvuruButton.setText("Kredi Başvuru");
        krediBasvuruButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krediBasvuruButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(600, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hesapButton)
                    .addComponent(krediBasvuruButton))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(paraTransferiButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(krediKartiButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(faturaButton)
                    .addComponent(sifreDegistirButton))
                .addGap(79, 79, 79))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paraTransferiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faturaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hesapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sifreDegistirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(krediKartiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(krediBasvuruButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addContainerGap())
        );

        fullNameText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fullNameText.setText("Ad Soyad");

        balanceText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        balanceText.setText("200 ₺");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(balanceText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(anaEkranText, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fullNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fullNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(balanceText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(anaEkranText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        new LoginJFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void hesapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesapButtonActionPerformed
        new HesapIslemleri(userData).setVisible(true);
        dispose();
    }//GEN-LAST:event_hesapButtonActionPerformed

    private void paraTransferiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paraTransferiButtonActionPerformed
        new MoneyTransfer(userData).setVisible(true);
        dispose();
    }//GEN-LAST:event_paraTransferiButtonActionPerformed

    private void faturaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faturaButtonActionPerformed
        new PayingBills(userData).setVisible(true);
        dispose();
    }//GEN-LAST:event_faturaButtonActionPerformed

    private void krediKartiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krediKartiButtonActionPerformed
        new CreditCardGUI(userData).setVisible(true);
        dispose();
    }//GEN-LAST:event_krediKartiButtonActionPerformed

    private void sifreDegistirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifreDegistirButtonActionPerformed
        new ChangePassword(userData).setVisible(true);
        dispose();
    }//GEN-LAST:event_sifreDegistirButtonActionPerformed

    private void krediBasvuruButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krediBasvuruButtonActionPerformed
        new CreditGUI(userData).setVisible(true);
        dispose();
    }//GEN-LAST:event_krediBasvuruButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String[] userData = {"id","ad soyad","200"};
                new CustomerDashboard(userData).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anaEkranText;
    private javax.swing.JLabel balanceText;
    private javax.swing.JButton faturaButton;
    private javax.swing.JLabel fullNameText;
    private javax.swing.JButton hesapButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton krediBasvuruButton;
    private javax.swing.JButton krediKartiButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton paraTransferiButton;
    private javax.swing.JButton sifreDegistirButton;
    // End of variables declaration//GEN-END:variables
}
